//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Program.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Frontend {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class ProgramParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, Whitespace=33, Newline=34, BlockComment=35, LineComment=36, 
		INT=37, SHORT=38, CHAR=39, VOID=40, IF=41, ELSE=42, WHILE=43, BREAK=44, 
		CONTINUE=45, RETURN=46, Id=47, Num=48;
	public const int
		RULE_program = 0, RULE_decl = 1, RULE_var_decl = 2, RULE_primary_expr = 3, 
		RULE_postfix_expr = 4, RULE_argument_expr_list = 5, RULE_unary_expr = 6, 
		RULE_assignmentExpr = 7, RULE_binaryExpr = 8, RULE_expr = 9, RULE_func_def = 10, 
		RULE_compound_stmt = 11, RULE_block_item_list = 12, RULE_block_item = 13, 
		RULE_param_list = 14, RULE_param = 15, RULE_stmt = 16, RULE_continue_stmt = 17, 
		RULE_break_stmt = 18, RULE_return_stmt = 19, RULE_expr_stmt = 20, RULE_selection_stmt = 21, 
		RULE_iteration_stmt = 22, RULE_num = 23, RULE_id = 24, RULE_type_spec = 25;
	public static readonly string[] ruleNames = {
		"program", "decl", "var_decl", "primary_expr", "postfix_expr", "argument_expr_list", 
		"unary_expr", "assignmentExpr", "binaryExpr", "expr", "func_def", "compound_stmt", 
		"block_item_list", "block_item", "param_list", "param", "stmt", "continue_stmt", 
		"break_stmt", "return_stmt", "expr_stmt", "selection_stmt", "iteration_stmt", 
		"num", "id", "type_spec"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'['", "']'", "'('", "')'", "','", "'++'", "'--'", "'$'", 
		"'!'", "'~'", "'='", "'*'", "'%'", "'/'", "'+'", "'-'", "'<<'", "'>>'", 
		"'<='", "'>='", "'<'", "'>'", "'=='", "'!='", "'&'", "'^'", "'|'", "'&&'", 
		"'||'", "'{'", "'}'", null, null, null, null, "'int'", "'short'", "'char'", 
		"'void'", "'if'", "'else'", "'while'", "'break'", "'continue'", "'return'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, "Whitespace", "Newline", 
		"BlockComment", "LineComment", "INT", "SHORT", "CHAR", "VOID", "IF", "ELSE", 
		"WHILE", "BREAK", "CONTINUE", "RETURN", "Id", "Num"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Program.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ProgramParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ProgramParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ProgramParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public DeclContext[] decl() {
			return GetRuleContexts<DeclContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DeclContext decl(int i) {
			return GetRuleContext<DeclContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 52;
				decl();
				}
				}
				State = 55;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INT) | (1L << SHORT) | (1L << CHAR) | (1L << VOID))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeclContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Var_declContext var_decl() {
			return GetRuleContext<Var_declContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_defContext func_def() {
			return GetRuleContext<Func_defContext>(0);
		}
		public DeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitDecl(this);
		}
	}

	[RuleVersion(0)]
	public DeclContext decl() {
		DeclContext _localctx = new DeclContext(Context, State);
		EnterRule(_localctx, 2, RULE_decl);
		try {
			State = 59;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 57;
				var_decl();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 58;
				func_def();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_declContext : ParserRuleContext {
		public Var_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_decl; } }
	 
		public Var_declContext() { }
		public virtual void CopyFrom(Var_declContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Var_declHasArrContext : Var_declContext {
		[System.Diagnostics.DebuggerNonUserCode] public Type_specContext type_spec() {
			return GetRuleContext<Type_specContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		public Var_declHasArrContext(Var_declContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterVar_declHasArr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitVar_declHasArr(this);
		}
	}
	public partial class Var_declHasIdContext : Var_declContext {
		[System.Diagnostics.DebuggerNonUserCode] public Type_specContext type_spec() {
			return GetRuleContext<Type_specContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public Var_declHasIdContext(Var_declContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterVar_declHasId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitVar_declHasId(this);
		}
	}

	[RuleVersion(0)]
	public Var_declContext var_decl() {
		Var_declContext _localctx = new Var_declContext(Context, State);
		EnterRule(_localctx, 4, RULE_var_decl);
		try {
			State = 72;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				_localctx = new Var_declHasIdContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 61;
				type_spec();
				State = 62;
				id();
				State = 63;
				Match(T__0);
				}
				}
				break;
			case 2:
				_localctx = new Var_declHasArrContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				{
				State = 65;
				type_spec();
				State = 66;
				id();
				State = 67;
				Match(T__1);
				State = 68;
				num();
				State = 69;
				Match(T__2);
				State = 70;
				Match(T__0);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Primary_exprContext : ParserRuleContext {
		public Primary_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_primary_expr; } }
	 
		public Primary_exprContext() { }
		public virtual void CopyFrom(Primary_exprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Primary_exprHasIdContext : Primary_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public Primary_exprHasIdContext(Primary_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterPrimary_exprHasId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitPrimary_exprHasId(this);
		}
	}
	public partial class Primary_exprHasExprContext : Primary_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Primary_exprHasExprContext(Primary_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterPrimary_exprHasExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitPrimary_exprHasExpr(this);
		}
	}
	public partial class Primary_exprHasNumContext : Primary_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		public Primary_exprHasNumContext(Primary_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterPrimary_exprHasNum(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitPrimary_exprHasNum(this);
		}
	}

	[RuleVersion(0)]
	public Primary_exprContext primary_expr() {
		Primary_exprContext _localctx = new Primary_exprContext(Context, State);
		EnterRule(_localctx, 6, RULE_primary_expr);
		try {
			State = 80;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				_localctx = new Primary_exprHasExprContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 74;
				Match(T__3);
				State = 75;
				expr();
				State = 76;
				Match(T__4);
				}
				break;
			case Id:
				_localctx = new Primary_exprHasIdContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 78;
				id();
				}
				break;
			case Num:
				_localctx = new Primary_exprHasNumContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 79;
				num();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Postfix_exprContext : ParserRuleContext {
		public Postfix_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_postfix_expr; } }
	 
		public Postfix_exprContext() { }
		public virtual void CopyFrom(Postfix_exprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Postfix_exprHasgetitemContext : Postfix_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public Primary_exprContext primary_expr() {
			return GetRuleContext<Primary_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Postfix_exprHasgetitemContext(Postfix_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterPostfix_exprHasgetitem(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitPostfix_exprHasgetitem(this);
		}
	}
	public partial class Postfix_exprHasPrimary_exprContext : Postfix_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public Primary_exprContext primary_expr() {
			return GetRuleContext<Primary_exprContext>(0);
		}
		public Postfix_exprHasPrimary_exprContext(Postfix_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterPostfix_exprHasPrimary_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitPostfix_exprHasPrimary_expr(this);
		}
	}
	public partial class Postfix_exprHasEmptyCallContext : Postfix_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public Postfix_exprHasEmptyCallContext(Postfix_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterPostfix_exprHasEmptyCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitPostfix_exprHasEmptyCall(this);
		}
	}
	public partial class Postfix_exprHasCallContext : Postfix_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Argument_expr_listContext argument_expr_list() {
			return GetRuleContext<Argument_expr_listContext>(0);
		}
		public Postfix_exprHasCallContext(Postfix_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterPostfix_exprHasCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitPostfix_exprHasCall(this);
		}
	}

	[RuleVersion(0)]
	public Postfix_exprContext postfix_expr() {
		Postfix_exprContext _localctx = new Postfix_exprContext(Context, State);
		EnterRule(_localctx, 8, RULE_postfix_expr);
		try {
			State = 97;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				_localctx = new Postfix_exprHasPrimary_exprContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 82;
				primary_expr();
				}
				break;
			case 2:
				_localctx = new Postfix_exprHasgetitemContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 83;
				primary_expr();
				State = 84;
				Match(T__1);
				State = 85;
				expr();
				State = 86;
				Match(T__2);
				}
				break;
			case 3:
				_localctx = new Postfix_exprHasEmptyCallContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 88;
				id();
				State = 89;
				Match(T__3);
				State = 90;
				Match(T__4);
				}
				break;
			case 4:
				_localctx = new Postfix_exprHasCallContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 92;
				id();
				State = 93;
				Match(T__3);
				State = 94;
				argument_expr_list();
				State = 95;
				Match(T__4);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Argument_expr_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public Argument_expr_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument_expr_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterArgument_expr_list(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitArgument_expr_list(this);
		}
	}

	[RuleVersion(0)]
	public Argument_expr_listContext argument_expr_list() {
		Argument_expr_listContext _localctx = new Argument_expr_listContext(Context, State);
		EnterRule(_localctx, 10, RULE_argument_expr_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99;
			expr();
			State = 104;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__5) {
				{
				{
				State = 100;
				Match(T__5);
				State = 101;
				expr();
				}
				}
				State = 106;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Unary_exprContext : ParserRuleContext {
		public Unary_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unary_expr; } }
	 
		public Unary_exprContext() { }
		public virtual void CopyFrom(Unary_exprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Unary_exprHasLNotContext : Unary_exprContext {
		public IToken prefix;
		[System.Diagnostics.DebuggerNonUserCode] public Unary_exprContext unary_expr() {
			return GetRuleContext<Unary_exprContext>(0);
		}
		public Unary_exprHasLNotContext(Unary_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterUnary_exprHasLNot(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitUnary_exprHasLNot(this);
		}
	}
	public partial class Unary_exprHasIncContext : Unary_exprContext {
		public IToken prefix;
		[System.Diagnostics.DebuggerNonUserCode] public Unary_exprContext unary_expr() {
			return GetRuleContext<Unary_exprContext>(0);
		}
		public Unary_exprHasIncContext(Unary_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterUnary_exprHasInc(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitUnary_exprHasInc(this);
		}
	}
	public partial class Unary_exprHasPostfix_exprContext : Unary_exprContext {
		[System.Diagnostics.DebuggerNonUserCode] public Postfix_exprContext postfix_expr() {
			return GetRuleContext<Postfix_exprContext>(0);
		}
		public Unary_exprHasPostfix_exprContext(Unary_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterUnary_exprHasPostfix_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitUnary_exprHasPostfix_expr(this);
		}
	}
	public partial class Unary_exprHasNotContext : Unary_exprContext {
		public IToken prefix;
		[System.Diagnostics.DebuggerNonUserCode] public Unary_exprContext unary_expr() {
			return GetRuleContext<Unary_exprContext>(0);
		}
		public Unary_exprHasNotContext(Unary_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterUnary_exprHasNot(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitUnary_exprHasNot(this);
		}
	}
	public partial class Unary_exprHasDolContext : Unary_exprContext {
		public IToken prefix;
		[System.Diagnostics.DebuggerNonUserCode] public Unary_exprContext unary_expr() {
			return GetRuleContext<Unary_exprContext>(0);
		}
		public Unary_exprHasDolContext(Unary_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterUnary_exprHasDol(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitUnary_exprHasDol(this);
		}
	}
	public partial class Unary_exprHasDecContext : Unary_exprContext {
		public IToken prefix;
		[System.Diagnostics.DebuggerNonUserCode] public Unary_exprContext unary_expr() {
			return GetRuleContext<Unary_exprContext>(0);
		}
		public Unary_exprHasDecContext(Unary_exprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterUnary_exprHasDec(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitUnary_exprHasDec(this);
		}
	}

	[RuleVersion(0)]
	public Unary_exprContext unary_expr() {
		Unary_exprContext _localctx = new Unary_exprContext(Context, State);
		EnterRule(_localctx, 12, RULE_unary_expr);
		try {
			State = 118;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
			case Id:
			case Num:
				_localctx = new Unary_exprHasPostfix_exprContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 107;
				postfix_expr();
				}
				break;
			case T__6:
				_localctx = new Unary_exprHasIncContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 108;
				((Unary_exprHasIncContext)_localctx).prefix = Match(T__6);
				State = 109;
				unary_expr();
				}
				break;
			case T__7:
				_localctx = new Unary_exprHasDecContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 110;
				((Unary_exprHasDecContext)_localctx).prefix = Match(T__7);
				State = 111;
				unary_expr();
				}
				break;
			case T__8:
				_localctx = new Unary_exprHasDolContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 112;
				((Unary_exprHasDolContext)_localctx).prefix = Match(T__8);
				State = 113;
				unary_expr();
				}
				break;
			case T__9:
				_localctx = new Unary_exprHasLNotContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 114;
				((Unary_exprHasLNotContext)_localctx).prefix = Match(T__9);
				State = 115;
				unary_expr();
				}
				break;
			case T__10:
				_localctx = new Unary_exprHasNotContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 116;
				((Unary_exprHasNotContext)_localctx).prefix = Match(T__10);
				State = 117;
				unary_expr();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentExprContext : ParserRuleContext {
		public AssignmentExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignmentExpr; } }
	 
		public AssignmentExprContext() { }
		public virtual void CopyFrom(AssignmentExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class AssignmentExprHasBinaryContext : AssignmentExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public BinaryExprContext binaryExpr() {
			return GetRuleContext<BinaryExprContext>(0);
		}
		public AssignmentExprHasBinaryContext(AssignmentExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterAssignmentExprHasBinary(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitAssignmentExprHasBinary(this);
		}
	}
	public partial class AssignmentExprHasAssignContext : AssignmentExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public Unary_exprContext unary_expr() {
			return GetRuleContext<Unary_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentExprContext assignmentExpr() {
			return GetRuleContext<AssignmentExprContext>(0);
		}
		public AssignmentExprHasAssignContext(AssignmentExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterAssignmentExprHasAssign(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitAssignmentExprHasAssign(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentExprContext assignmentExpr() {
		AssignmentExprContext _localctx = new AssignmentExprContext(Context, State);
		EnterRule(_localctx, 14, RULE_assignmentExpr);
		try {
			State = 125;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				_localctx = new AssignmentExprHasBinaryContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 120;
				binaryExpr(0);
				}
				break;
			case 2:
				_localctx = new AssignmentExprHasAssignContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 121;
				unary_expr();
				State = 122;
				Match(T__11);
				State = 123;
				assignmentExpr();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BinaryExprContext : ParserRuleContext {
		public BinaryExprContext left;
		public IToken op;
		public BinaryExprContext right;
		[System.Diagnostics.DebuggerNonUserCode] public Unary_exprContext unary_expr() {
			return GetRuleContext<Unary_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BinaryExprContext[] binaryExpr() {
			return GetRuleContexts<BinaryExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public BinaryExprContext binaryExpr(int i) {
			return GetRuleContext<BinaryExprContext>(i);
		}
		public BinaryExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_binaryExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterBinaryExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitBinaryExpr(this);
		}
	}

	[RuleVersion(0)]
	public BinaryExprContext binaryExpr() {
		return binaryExpr(0);
	}

	private BinaryExprContext binaryExpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		BinaryExprContext _localctx = new BinaryExprContext(Context, _parentState);
		BinaryExprContext _prevctx = _localctx;
		int _startState = 16;
		EnterRecursionRule(_localctx, 16, RULE_binaryExpr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 130;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				{
				State = 128;
				unary_expr();
				}
				break;
			case 2:
				{
				State = 129;
				num();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 188;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 186;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
					case 1:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 132;
						if (!(Precpred(Context, 20))) throw new FailedPredicateException(this, "Precpred(Context, 20)");
						State = 133;
						_localctx.op = Match(T__12);
						State = 134;
						_localctx.right = binaryExpr(21);
						}
						break;
					case 2:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 135;
						if (!(Precpred(Context, 19))) throw new FailedPredicateException(this, "Precpred(Context, 19)");
						State = 136;
						_localctx.op = Match(T__13);
						State = 137;
						_localctx.right = binaryExpr(20);
						}
						break;
					case 3:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 138;
						if (!(Precpred(Context, 18))) throw new FailedPredicateException(this, "Precpred(Context, 18)");
						State = 139;
						_localctx.op = Match(T__14);
						State = 140;
						_localctx.right = binaryExpr(19);
						}
						break;
					case 4:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 141;
						if (!(Precpred(Context, 17))) throw new FailedPredicateException(this, "Precpred(Context, 17)");
						State = 142;
						_localctx.op = Match(T__15);
						State = 143;
						_localctx.right = binaryExpr(18);
						}
						break;
					case 5:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 144;
						if (!(Precpred(Context, 16))) throw new FailedPredicateException(this, "Precpred(Context, 16)");
						State = 145;
						_localctx.op = Match(T__16);
						State = 146;
						_localctx.right = binaryExpr(17);
						}
						break;
					case 6:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 147;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 148;
						_localctx.op = Match(T__17);
						State = 149;
						_localctx.right = binaryExpr(16);
						}
						break;
					case 7:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 150;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 151;
						_localctx.op = Match(T__18);
						State = 152;
						_localctx.right = binaryExpr(15);
						}
						break;
					case 8:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 153;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 154;
						_localctx.op = Match(T__19);
						State = 155;
						_localctx.right = binaryExpr(14);
						}
						break;
					case 9:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 156;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 157;
						_localctx.op = Match(T__20);
						State = 158;
						_localctx.right = binaryExpr(13);
						}
						break;
					case 10:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 159;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 160;
						_localctx.op = Match(T__21);
						State = 161;
						_localctx.right = binaryExpr(12);
						}
						break;
					case 11:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 162;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 163;
						_localctx.op = Match(T__22);
						State = 164;
						_localctx.right = binaryExpr(11);
						}
						break;
					case 12:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 165;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 166;
						_localctx.op = Match(T__23);
						State = 167;
						_localctx.right = binaryExpr(10);
						}
						break;
					case 13:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 168;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 169;
						_localctx.op = Match(T__24);
						State = 170;
						_localctx.right = binaryExpr(9);
						}
						break;
					case 14:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 171;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 172;
						_localctx.op = Match(T__25);
						State = 173;
						_localctx.right = binaryExpr(8);
						}
						break;
					case 15:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 174;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 175;
						_localctx.op = Match(T__26);
						State = 176;
						_localctx.right = binaryExpr(7);
						}
						break;
					case 16:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 177;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 178;
						_localctx.op = Match(T__27);
						State = 179;
						_localctx.right = binaryExpr(6);
						}
						break;
					case 17:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 180;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 181;
						_localctx.op = Match(T__28);
						State = 182;
						_localctx.right = binaryExpr(5);
						}
						break;
					case 18:
						{
						_localctx = new BinaryExprContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_binaryExpr);
						State = 183;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 184;
						_localctx.op = Match(T__29);
						State = 185;
						_localctx.right = binaryExpr(4);
						}
						break;
					}
					} 
				}
				State = 190;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentExprContext assignmentExpr() {
			return GetRuleContext<AssignmentExprContext>(0);
		}
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		ExprContext _localctx = new ExprContext(Context, State);
		EnterRule(_localctx, 18, RULE_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 191;
			assignmentExpr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_defContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Param_listContext param_list() {
			return GetRuleContext<Param_listContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Compound_stmtContext compound_stmt() {
			return GetRuleContext<Compound_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_specContext type_spec() {
			return GetRuleContext<Type_specContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VOID() { return GetToken(ProgramParser.VOID, 0); }
		public Func_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_def; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterFunc_def(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitFunc_def(this);
		}
	}

	[RuleVersion(0)]
	public Func_defContext func_def() {
		Func_defContext _localctx = new Func_defContext(Context, State);
		EnterRule(_localctx, 20, RULE_func_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 195;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
			case SHORT:
			case CHAR:
				{
				State = 193;
				type_spec();
				}
				break;
			case VOID:
				{
				State = 194;
				Match(VOID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 197;
			id();
			State = 198;
			param_list();
			State = 199;
			compound_stmt();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Compound_stmtContext : ParserRuleContext {
		public Compound_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compound_stmt; } }
	 
		public Compound_stmtContext() { }
		public virtual void CopyFrom(Compound_stmtContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Compound_stmtHasBodyContext : Compound_stmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public Block_item_listContext block_item_list() {
			return GetRuleContext<Block_item_listContext>(0);
		}
		public Compound_stmtHasBodyContext(Compound_stmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterCompound_stmtHasBody(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitCompound_stmtHasBody(this);
		}
	}
	public partial class Compound_stmtHasEmptyContext : Compound_stmtContext {
		public Compound_stmtHasEmptyContext(Compound_stmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterCompound_stmtHasEmpty(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitCompound_stmtHasEmpty(this);
		}
	}

	[RuleVersion(0)]
	public Compound_stmtContext compound_stmt() {
		Compound_stmtContext _localctx = new Compound_stmtContext(Context, State);
		EnterRule(_localctx, 22, RULE_compound_stmt);
		try {
			State = 207;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				_localctx = new Compound_stmtHasEmptyContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 201;
				Match(T__30);
				State = 202;
				Match(T__31);
				}
				break;
			case 2:
				_localctx = new Compound_stmtHasBodyContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 203;
				Match(T__30);
				State = 204;
				block_item_list();
				State = 205;
				Match(T__31);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Block_item_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Block_itemContext[] block_item() {
			return GetRuleContexts<Block_itemContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Block_itemContext block_item(int i) {
			return GetRuleContext<Block_itemContext>(i);
		}
		public Block_item_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block_item_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterBlock_item_list(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitBlock_item_list(this);
		}
	}

	[RuleVersion(0)]
	public Block_item_listContext block_item_list() {
		Block_item_listContext _localctx = new Block_item_listContext(Context, State);
		EnterRule(_localctx, 24, RULE_block_item_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 210;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 209;
				block_item();
				}
				}
				State = 212;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__3) | (1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__30) | (1L << INT) | (1L << SHORT) | (1L << CHAR) | (1L << IF) | (1L << WHILE) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << Id) | (1L << Num))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Block_itemContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Var_declContext var_decl() {
			return GetRuleContext<Var_declContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		public Block_itemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block_item; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterBlock_item(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitBlock_item(this);
		}
	}

	[RuleVersion(0)]
	public Block_itemContext block_item() {
		Block_itemContext _localctx = new Block_itemContext(Context, State);
		EnterRule(_localctx, 26, RULE_block_item);
		try {
			State = 216;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
			case SHORT:
			case CHAR:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 214;
				var_decl();
				}
				}
				break;
			case T__3:
			case T__6:
			case T__7:
			case T__8:
			case T__9:
			case T__10:
			case T__30:
			case IF:
			case WHILE:
			case BREAK:
			case CONTINUE:
			case RETURN:
			case Id:
			case Num:
				EnterOuterAlt(_localctx, 2);
				{
				{
				State = 215;
				stmt();
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Param_listContext : ParserRuleContext {
		public Param_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_param_list; } }
	 
		public Param_listContext() { }
		public virtual void CopyFrom(Param_listContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Param_listHasEmptyContext : Param_listContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VOID() { return GetToken(ProgramParser.VOID, 0); }
		public Param_listHasEmptyContext(Param_listContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterParam_listHasEmpty(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitParam_listHasEmpty(this);
		}
	}
	public partial class Param_listHasBodyContext : Param_listContext {
		[System.Diagnostics.DebuggerNonUserCode] public ParamContext[] param() {
			return GetRuleContexts<ParamContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ParamContext param(int i) {
			return GetRuleContext<ParamContext>(i);
		}
		public Param_listHasBodyContext(Param_listContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterParam_listHasBody(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitParam_listHasBody(this);
		}
	}

	[RuleVersion(0)]
	public Param_listContext param_list() {
		Param_listContext _localctx = new Param_listContext(Context, State);
		EnterRule(_localctx, 28, RULE_param_list);
		int _la;
		try {
			State = 234;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
			case 1:
				_localctx = new Param_listHasEmptyContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 218;
				Match(T__3);
				State = 220;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==VOID) {
					{
					State = 219;
					Match(VOID);
					}
				}

				State = 222;
				Match(T__4);
				}
				break;
			case 2:
				_localctx = new Param_listHasBodyContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 223;
				Match(T__3);
				State = 224;
				param();
				State = 229;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 225;
					Match(T__5);
					State = 226;
					param();
					}
					}
					State = 231;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 232;
				Match(T__4);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParamContext : ParserRuleContext {
		public ParamContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_param; } }
	 
		public ParamContext() { }
		public virtual void CopyFrom(ParamContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ParamHasArrContext : ParamContext {
		[System.Diagnostics.DebuggerNonUserCode] public Type_specContext type_spec() {
			return GetRuleContext<Type_specContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumContext num() {
			return GetRuleContext<NumContext>(0);
		}
		public ParamHasArrContext(ParamContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterParamHasArr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitParamHasArr(this);
		}
	}
	public partial class ParamHasIntContext : ParamContext {
		[System.Diagnostics.DebuggerNonUserCode] public Type_specContext type_spec() {
			return GetRuleContext<Type_specContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public ParamHasIntContext(ParamContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterParamHasInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitParamHasInt(this);
		}
	}

	[RuleVersion(0)]
	public ParamContext param() {
		ParamContext _localctx = new ParamContext(Context, State);
		EnterRule(_localctx, 30, RULE_param);
		int _la;
		try {
			State = 247;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				_localctx = new ParamHasIntContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 236;
				type_spec();
				State = 237;
				id();
				}
				break;
			case 2:
				_localctx = new ParamHasArrContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 239;
				type_spec();
				State = 240;
				id();
				State = 241;
				Match(T__1);
				State = 243;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Num) {
					{
					State = 242;
					num();
					}
				}

				State = 245;
				Match(T__2);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Selection_stmtContext selection_stmt() {
			return GetRuleContext<Selection_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Iteration_stmtContext iteration_stmt() {
			return GetRuleContext<Iteration_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Return_stmtContext return_stmt() {
			return GetRuleContext<Return_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Continue_stmtContext continue_stmt() {
			return GetRuleContext<Continue_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Break_stmtContext break_stmt() {
			return GetRuleContext<Break_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Compound_stmtContext compound_stmt() {
			return GetRuleContext<Compound_stmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expr_stmtContext expr_stmt() {
			return GetRuleContext<Expr_stmtContext>(0);
		}
		public StmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterStmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitStmt(this);
		}
	}

	[RuleVersion(0)]
	public StmtContext stmt() {
		StmtContext _localctx = new StmtContext(Context, State);
		EnterRule(_localctx, 32, RULE_stmt);
		try {
			State = 256;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IF:
				EnterOuterAlt(_localctx, 1);
				{
				State = 249;
				selection_stmt();
				}
				break;
			case WHILE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 250;
				iteration_stmt();
				}
				break;
			case RETURN:
				EnterOuterAlt(_localctx, 3);
				{
				State = 251;
				return_stmt();
				}
				break;
			case CONTINUE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 252;
				continue_stmt();
				}
				break;
			case BREAK:
				EnterOuterAlt(_localctx, 5);
				{
				State = 253;
				break_stmt();
				}
				break;
			case T__30:
				EnterOuterAlt(_localctx, 6);
				{
				State = 254;
				compound_stmt();
				}
				break;
			case T__3:
			case T__6:
			case T__7:
			case T__8:
			case T__9:
			case T__10:
			case Id:
			case Num:
				EnterOuterAlt(_localctx, 7);
				{
				State = 255;
				expr_stmt();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Continue_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONTINUE() { return GetToken(ProgramParser.CONTINUE, 0); }
		public Continue_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_continue_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterContinue_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitContinue_stmt(this);
		}
	}

	[RuleVersion(0)]
	public Continue_stmtContext continue_stmt() {
		Continue_stmtContext _localctx = new Continue_stmtContext(Context, State);
		EnterRule(_localctx, 34, RULE_continue_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 258;
			Match(CONTINUE);
			State = 259;
			Match(T__0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Break_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BREAK() { return GetToken(ProgramParser.BREAK, 0); }
		public Break_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_break_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterBreak_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitBreak_stmt(this);
		}
	}

	[RuleVersion(0)]
	public Break_stmtContext break_stmt() {
		Break_stmtContext _localctx = new Break_stmtContext(Context, State);
		EnterRule(_localctx, 36, RULE_break_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 261;
			Match(BREAK);
			State = 262;
			Match(T__0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Return_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN() { return GetToken(ProgramParser.RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Return_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_return_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterReturn_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitReturn_stmt(this);
		}
	}

	[RuleVersion(0)]
	public Return_stmtContext return_stmt() {
		Return_stmtContext _localctx = new Return_stmtContext(Context, State);
		EnterRule(_localctx, 38, RULE_return_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 264;
			Match(RETURN);
			State = 265;
			expr();
			State = 266;
			Match(T__0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expr_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Expr_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterExpr_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitExpr_stmt(this);
		}
	}

	[RuleVersion(0)]
	public Expr_stmtContext expr_stmt() {
		Expr_stmtContext _localctx = new Expr_stmtContext(Context, State);
		EnterRule(_localctx, 40, RULE_expr_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 268;
			expr();
			State = 269;
			Match(T__0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Selection_stmtContext : ParserRuleContext {
		public Selection_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selection_stmt; } }
	 
		public Selection_stmtContext() { }
		public virtual void CopyFrom(Selection_stmtContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Selection_stmtHasEmptyContext : Selection_stmtContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(ProgramParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		public Selection_stmtHasEmptyContext(Selection_stmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterSelection_stmtHasEmpty(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitSelection_stmtHasEmpty(this);
		}
	}
	public partial class Selection_stmtHasElseContext : Selection_stmtContext {
		public StmtContext ifStmt;
		public StmtContext elseStmt;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(ProgramParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(ProgramParser.ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public Selection_stmtHasElseContext(Selection_stmtContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterSelection_stmtHasElse(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitSelection_stmtHasElse(this);
		}
	}

	[RuleVersion(0)]
	public Selection_stmtContext selection_stmt() {
		Selection_stmtContext _localctx = new Selection_stmtContext(Context, State);
		EnterRule(_localctx, 42, RULE_selection_stmt);
		try {
			State = 285;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
			case 1:
				_localctx = new Selection_stmtHasElseContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 271;
				Match(IF);
				State = 272;
				Match(T__3);
				State = 273;
				expr();
				State = 274;
				Match(T__4);
				State = 275;
				((Selection_stmtHasElseContext)_localctx).ifStmt = stmt();
				State = 276;
				Match(ELSE);
				State = 277;
				((Selection_stmtHasElseContext)_localctx).elseStmt = stmt();
				}
				break;
			case 2:
				_localctx = new Selection_stmtHasEmptyContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 279;
				Match(IF);
				State = 280;
				Match(T__3);
				State = 281;
				expr();
				State = 282;
				Match(T__4);
				State = 283;
				stmt();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Iteration_stmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE() { return GetToken(ProgramParser.WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		public Iteration_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_iteration_stmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterIteration_stmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitIteration_stmt(this);
		}
	}

	[RuleVersion(0)]
	public Iteration_stmtContext iteration_stmt() {
		Iteration_stmtContext _localctx = new Iteration_stmtContext(Context, State);
		EnterRule(_localctx, 44, RULE_iteration_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 287;
			Match(WHILE);
			State = 288;
			Match(T__3);
			State = 289;
			expr();
			State = 290;
			Match(T__4);
			State = 291;
			stmt();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Num() { return GetToken(ProgramParser.Num, 0); }
		public NumContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_num; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterNum(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitNum(this);
		}
	}

	[RuleVersion(0)]
	public NumContext num() {
		NumContext _localctx = new NumContext(Context, State);
		EnterRule(_localctx, 46, RULE_num);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 293;
			Match(Num);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Id() { return GetToken(ProgramParser.Id, 0); }
		public IdContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_id; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitId(this);
		}
	}

	[RuleVersion(0)]
	public IdContext id() {
		IdContext _localctx = new IdContext(Context, State);
		EnterRule(_localctx, 48, RULE_id);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 295;
			Match(Id);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_specContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(ProgramParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SHORT() { return GetToken(ProgramParser.SHORT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHAR() { return GetToken(ProgramParser.CHAR, 0); }
		public Type_specContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_spec; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterType_spec(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitType_spec(this);
		}
	}

	[RuleVersion(0)]
	public Type_specContext type_spec() {
		Type_specContext _localctx = new Type_specContext(Context, State);
		EnterRule(_localctx, 50, RULE_type_spec);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 297;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INT) | (1L << SHORT) | (1L << CHAR))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 8: return binaryExpr_sempred((BinaryExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool binaryExpr_sempred(BinaryExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 20);
		case 1: return Precpred(Context, 19);
		case 2: return Precpred(Context, 18);
		case 3: return Precpred(Context, 17);
		case 4: return Precpred(Context, 16);
		case 5: return Precpred(Context, 15);
		case 6: return Precpred(Context, 14);
		case 7: return Precpred(Context, 13);
		case 8: return Precpred(Context, 12);
		case 9: return Precpred(Context, 11);
		case 10: return Precpred(Context, 10);
		case 11: return Precpred(Context, 9);
		case 12: return Precpred(Context, 8);
		case 13: return Precpred(Context, 7);
		case 14: return Precpred(Context, 6);
		case 15: return Precpred(Context, 5);
		case 16: return Precpred(Context, 4);
		case 17: return Precpred(Context, 3);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x32', '\x12E', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x3', '\x2', '\x6', '\x2', '\x38', '\n', '\x2', 
		'\r', '\x2', '\xE', '\x2', '\x39', '\x3', '\x3', '\x3', '\x3', '\x5', 
		'\x3', '>', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', 'K', '\n', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x5', '\x5', 'S', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '\x64', '\n', '\x6', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\a', '\a', 'i', '\n', '\a', '\f', 
		'\a', '\xE', '\a', 'l', '\v', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', 'y', '\n', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\x80', 
		'\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', '\x85', 
		'\n', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\a', '\n', '\xBD', '\n', '\n', '\f', '\n', '\xE', '\n', '\xC0', '\v', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x5', '\f', 
		'\xC6', '\n', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x5', '\r', '\xD2', '\n', '\r', '\x3', '\xE', '\x6', '\xE', '\xD5', 
		'\n', '\xE', '\r', '\xE', '\xE', '\xE', '\xD6', '\x3', '\xF', '\x3', '\xF', 
		'\x5', '\xF', '\xDB', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', '\x5', 
		'\x10', '\xDF', '\n', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\a', '\x10', '\xE6', '\n', '\x10', '\f', 
		'\x10', '\xE', '\x10', '\xE9', '\v', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x5', '\x10', '\xED', '\n', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', 
		'\x11', '\xF6', '\n', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', '\x11', 
		'\xFA', '\n', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', '\x103', 
		'\n', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x5', '\x17', '\x120', '\n', 
		'\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x2', '\x3', '\x12', 
		'\x1C', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', 
		'\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', 
		'*', ',', '.', '\x30', '\x32', '\x34', '\x2', '\x3', '\x3', '\x2', '\'', 
		')', '\x2', '\x145', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x4', 
		'=', '\x3', '\x2', '\x2', '\x2', '\x6', 'J', '\x3', '\x2', '\x2', '\x2', 
		'\b', 'R', '\x3', '\x2', '\x2', '\x2', '\n', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\f', '\x65', '\x3', '\x2', '\x2', '\x2', '\xE', 'x', '\x3', '\x2', 
		'\x2', '\x2', '\x10', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x12', '\x84', 
		'\x3', '\x2', '\x2', '\x2', '\x14', '\xC1', '\x3', '\x2', '\x2', '\x2', 
		'\x16', '\xC5', '\x3', '\x2', '\x2', '\x2', '\x18', '\xD1', '\x3', '\x2', 
		'\x2', '\x2', '\x1A', '\xD4', '\x3', '\x2', '\x2', '\x2', '\x1C', '\xDA', 
		'\x3', '\x2', '\x2', '\x2', '\x1E', '\xEC', '\x3', '\x2', '\x2', '\x2', 
		' ', '\xF9', '\x3', '\x2', '\x2', '\x2', '\"', '\x102', '\x3', '\x2', 
		'\x2', '\x2', '$', '\x104', '\x3', '\x2', '\x2', '\x2', '&', '\x107', 
		'\x3', '\x2', '\x2', '\x2', '(', '\x10A', '\x3', '\x2', '\x2', '\x2', 
		'*', '\x10E', '\x3', '\x2', '\x2', '\x2', ',', '\x11F', '\x3', '\x2', 
		'\x2', '\x2', '.', '\x121', '\x3', '\x2', '\x2', '\x2', '\x30', '\x127', 
		'\x3', '\x2', '\x2', '\x2', '\x32', '\x129', '\x3', '\x2', '\x2', '\x2', 
		'\x34', '\x12B', '\x3', '\x2', '\x2', '\x2', '\x36', '\x38', '\x5', '\x4', 
		'\x3', '\x2', '\x37', '\x36', '\x3', '\x2', '\x2', '\x2', '\x38', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\x39', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\x39', ':', '\x3', '\x2', '\x2', '\x2', ':', '\x3', '\x3', '\x2', '\x2', 
		'\x2', ';', '>', '\x5', '\x6', '\x4', '\x2', '<', '>', '\x5', '\x16', 
		'\f', '\x2', '=', ';', '\x3', '\x2', '\x2', '\x2', '=', '<', '\x3', '\x2', 
		'\x2', '\x2', '>', '\x5', '\x3', '\x2', '\x2', '\x2', '?', '@', '\x5', 
		'\x34', '\x1B', '\x2', '@', '\x41', '\x5', '\x32', '\x1A', '\x2', '\x41', 
		'\x42', '\a', '\x3', '\x2', '\x2', '\x42', 'K', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\x44', '\x5', '\x34', '\x1B', '\x2', '\x44', '\x45', '\x5', '\x32', 
		'\x1A', '\x2', '\x45', '\x46', '\a', '\x4', '\x2', '\x2', '\x46', 'G', 
		'\x5', '\x30', '\x19', '\x2', 'G', 'H', '\a', '\x5', '\x2', '\x2', 'H', 
		'I', '\a', '\x3', '\x2', '\x2', 'I', 'K', '\x3', '\x2', '\x2', '\x2', 
		'J', '?', '\x3', '\x2', '\x2', '\x2', 'J', '\x43', '\x3', '\x2', '\x2', 
		'\x2', 'K', '\a', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\a', '\x6', '\x2', 
		'\x2', 'M', 'N', '\x5', '\x14', '\v', '\x2', 'N', 'O', '\a', '\a', '\x2', 
		'\x2', 'O', 'S', '\x3', '\x2', '\x2', '\x2', 'P', 'S', '\x5', '\x32', 
		'\x1A', '\x2', 'Q', 'S', '\x5', '\x30', '\x19', '\x2', 'R', 'L', '\x3', 
		'\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', '\x2', 'R', 'Q', '\x3', 
		'\x2', '\x2', '\x2', 'S', '\t', '\x3', '\x2', '\x2', '\x2', 'T', '\x64', 
		'\x5', '\b', '\x5', '\x2', 'U', 'V', '\x5', '\b', '\x5', '\x2', 'V', 'W', 
		'\a', '\x4', '\x2', '\x2', 'W', 'X', '\x5', '\x14', '\v', '\x2', 'X', 
		'Y', '\a', '\x5', '\x2', '\x2', 'Y', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'Z', '[', '\x5', '\x32', '\x1A', '\x2', '[', '\\', '\a', '\x6', '\x2', 
		'\x2', '\\', ']', '\a', '\a', '\x2', '\x2', ']', '\x64', '\x3', '\x2', 
		'\x2', '\x2', '^', '_', '\x5', '\x32', '\x1A', '\x2', '_', '`', '\a', 
		'\x6', '\x2', '\x2', '`', '\x61', '\x5', '\f', '\a', '\x2', '\x61', '\x62', 
		'\a', '\a', '\x2', '\x2', '\x62', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'\x63', 'T', '\x3', '\x2', '\x2', '\x2', '\x63', 'U', '\x3', '\x2', '\x2', 
		'\x2', '\x63', 'Z', '\x3', '\x2', '\x2', '\x2', '\x63', '^', '\x3', '\x2', 
		'\x2', '\x2', '\x64', '\v', '\x3', '\x2', '\x2', '\x2', '\x65', 'j', '\x5', 
		'\x14', '\v', '\x2', '\x66', 'g', '\a', '\b', '\x2', '\x2', 'g', 'i', 
		'\x5', '\x14', '\v', '\x2', 'h', '\x66', '\x3', '\x2', '\x2', '\x2', 'i', 
		'l', '\x3', '\x2', '\x2', '\x2', 'j', 'h', '\x3', '\x2', '\x2', '\x2', 
		'j', 'k', '\x3', '\x2', '\x2', '\x2', 'k', '\r', '\x3', '\x2', '\x2', 
		'\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 'm', 'y', '\x5', '\n', '\x6', 
		'\x2', 'n', 'o', '\a', '\t', '\x2', '\x2', 'o', 'y', '\x5', '\xE', '\b', 
		'\x2', 'p', 'q', '\a', '\n', '\x2', '\x2', 'q', 'y', '\x5', '\xE', '\b', 
		'\x2', 'r', 's', '\a', '\v', '\x2', '\x2', 's', 'y', '\x5', '\xE', '\b', 
		'\x2', 't', 'u', '\a', '\f', '\x2', '\x2', 'u', 'y', '\x5', '\xE', '\b', 
		'\x2', 'v', 'w', '\a', '\r', '\x2', '\x2', 'w', 'y', '\x5', '\xE', '\b', 
		'\x2', 'x', 'm', '\x3', '\x2', '\x2', '\x2', 'x', 'n', '\x3', '\x2', '\x2', 
		'\x2', 'x', 'p', '\x3', '\x2', '\x2', '\x2', 'x', 'r', '\x3', '\x2', '\x2', 
		'\x2', 'x', 't', '\x3', '\x2', '\x2', '\x2', 'x', 'v', '\x3', '\x2', '\x2', 
		'\x2', 'y', '\xF', '\x3', '\x2', '\x2', '\x2', 'z', '\x80', '\x5', '\x12', 
		'\n', '\x2', '{', '|', '\x5', '\xE', '\b', '\x2', '|', '}', '\a', '\xE', 
		'\x2', '\x2', '}', '~', '\x5', '\x10', '\t', '\x2', '~', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '\x7F', 'z', '\x3', '\x2', '\x2', '\x2', '\x7F', 
		'{', '\x3', '\x2', '\x2', '\x2', '\x80', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x82', '\b', '\n', '\x1', '\x2', '\x82', '\x85', '\x5', 
		'\xE', '\b', '\x2', '\x83', '\x85', '\x5', '\x30', '\x19', '\x2', '\x84', 
		'\x81', '\x3', '\x2', '\x2', '\x2', '\x84', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '\xBE', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\f', 
		'\x16', '\x2', '\x2', '\x87', '\x88', '\a', '\xF', '\x2', '\x2', '\x88', 
		'\xBD', '\x5', '\x12', '\n', '\x17', '\x89', '\x8A', '\f', '\x15', '\x2', 
		'\x2', '\x8A', '\x8B', '\a', '\x10', '\x2', '\x2', '\x8B', '\xBD', '\x5', 
		'\x12', '\n', '\x16', '\x8C', '\x8D', '\f', '\x14', '\x2', '\x2', '\x8D', 
		'\x8E', '\a', '\x11', '\x2', '\x2', '\x8E', '\xBD', '\x5', '\x12', '\n', 
		'\x15', '\x8F', '\x90', '\f', '\x13', '\x2', '\x2', '\x90', '\x91', '\a', 
		'\x12', '\x2', '\x2', '\x91', '\xBD', '\x5', '\x12', '\n', '\x14', '\x92', 
		'\x93', '\f', '\x12', '\x2', '\x2', '\x93', '\x94', '\a', '\x13', '\x2', 
		'\x2', '\x94', '\xBD', '\x5', '\x12', '\n', '\x13', '\x95', '\x96', '\f', 
		'\x11', '\x2', '\x2', '\x96', '\x97', '\a', '\x14', '\x2', '\x2', '\x97', 
		'\xBD', '\x5', '\x12', '\n', '\x12', '\x98', '\x99', '\f', '\x10', '\x2', 
		'\x2', '\x99', '\x9A', '\a', '\x15', '\x2', '\x2', '\x9A', '\xBD', '\x5', 
		'\x12', '\n', '\x11', '\x9B', '\x9C', '\f', '\xF', '\x2', '\x2', '\x9C', 
		'\x9D', '\a', '\x16', '\x2', '\x2', '\x9D', '\xBD', '\x5', '\x12', '\n', 
		'\x10', '\x9E', '\x9F', '\f', '\xE', '\x2', '\x2', '\x9F', '\xA0', '\a', 
		'\x17', '\x2', '\x2', '\xA0', '\xBD', '\x5', '\x12', '\n', '\xF', '\xA1', 
		'\xA2', '\f', '\r', '\x2', '\x2', '\xA2', '\xA3', '\a', '\x18', '\x2', 
		'\x2', '\xA3', '\xBD', '\x5', '\x12', '\n', '\xE', '\xA4', '\xA5', '\f', 
		'\f', '\x2', '\x2', '\xA5', '\xA6', '\a', '\x19', '\x2', '\x2', '\xA6', 
		'\xBD', '\x5', '\x12', '\n', '\r', '\xA7', '\xA8', '\f', '\v', '\x2', 
		'\x2', '\xA8', '\xA9', '\a', '\x1A', '\x2', '\x2', '\xA9', '\xBD', '\x5', 
		'\x12', '\n', '\f', '\xAA', '\xAB', '\f', '\n', '\x2', '\x2', '\xAB', 
		'\xAC', '\a', '\x1B', '\x2', '\x2', '\xAC', '\xBD', '\x5', '\x12', '\n', 
		'\v', '\xAD', '\xAE', '\f', '\t', '\x2', '\x2', '\xAE', '\xAF', '\a', 
		'\x1C', '\x2', '\x2', '\xAF', '\xBD', '\x5', '\x12', '\n', '\n', '\xB0', 
		'\xB1', '\f', '\b', '\x2', '\x2', '\xB1', '\xB2', '\a', '\x1D', '\x2', 
		'\x2', '\xB2', '\xBD', '\x5', '\x12', '\n', '\t', '\xB3', '\xB4', '\f', 
		'\a', '\x2', '\x2', '\xB4', '\xB5', '\a', '\x1E', '\x2', '\x2', '\xB5', 
		'\xBD', '\x5', '\x12', '\n', '\b', '\xB6', '\xB7', '\f', '\x6', '\x2', 
		'\x2', '\xB7', '\xB8', '\a', '\x1F', '\x2', '\x2', '\xB8', '\xBD', '\x5', 
		'\x12', '\n', '\a', '\xB9', '\xBA', '\f', '\x5', '\x2', '\x2', '\xBA', 
		'\xBB', '\a', ' ', '\x2', '\x2', '\xBB', '\xBD', '\x5', '\x12', '\n', 
		'\x6', '\xBC', '\x86', '\x3', '\x2', '\x2', '\x2', '\xBC', '\x89', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\x8C', '\x3', '\x2', '\x2', '\x2', '\xBC', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '\xBC', '\x92', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', '\x95', '\x3', '\x2', '\x2', '\x2', '\xBC', '\x98', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\x9B', '\x3', '\x2', '\x2', '\x2', '\xBC', 
		'\x9E', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xA1', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xA7', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xBC', 
		'\xAD', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xB6', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBD', 
		'\xC0', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xBF', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\xC0', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC1', 
		'\xC2', '\x5', '\x10', '\t', '\x2', '\xC2', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\xC3', '\xC6', '\x5', '\x34', '\x1B', '\x2', '\xC4', '\xC6', '\a', 
		'*', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC5', 
		'\xC4', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC7', '\x3', '\x2', '\x2', 
		'\x2', '\xC7', '\xC8', '\x5', '\x32', '\x1A', '\x2', '\xC8', '\xC9', '\x5', 
		'\x1E', '\x10', '\x2', '\xC9', '\xCA', '\x5', '\x18', '\r', '\x2', '\xCA', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xCC', '\a', '!', '\x2', 
		'\x2', '\xCC', '\xD2', '\a', '\"', '\x2', '\x2', '\xCD', '\xCE', '\a', 
		'!', '\x2', '\x2', '\xCE', '\xCF', '\x5', '\x1A', '\xE', '\x2', '\xCF', 
		'\xD0', '\a', '\"', '\x2', '\x2', '\xD0', '\xD2', '\x3', '\x2', '\x2', 
		'\x2', '\xD1', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xCD', '\x3', 
		'\x2', '\x2', '\x2', '\xD2', '\x19', '\x3', '\x2', '\x2', '\x2', '\xD3', 
		'\xD5', '\x5', '\x1C', '\xF', '\x2', '\xD4', '\xD3', '\x3', '\x2', '\x2', 
		'\x2', '\xD5', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD4', '\x3', 
		'\x2', '\x2', '\x2', '\xD6', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xD7', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xDB', '\x5', '\x6', '\x4', 
		'\x2', '\xD9', '\xDB', '\x5', '\"', '\x12', '\x2', '\xDA', '\xD8', '\x3', 
		'\x2', '\x2', '\x2', '\xDA', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xDB', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDE', '\a', '\x6', '\x2', 
		'\x2', '\xDD', '\xDF', '\a', '*', '\x2', '\x2', '\xDE', '\xDD', '\x3', 
		'\x2', '\x2', '\x2', '\xDE', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xDF', 
		'\xE0', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xED', '\a', '\a', '\x2', 
		'\x2', '\xE1', '\xE2', '\a', '\x6', '\x2', '\x2', '\xE2', '\xE7', '\x5', 
		' ', '\x11', '\x2', '\xE3', '\xE4', '\a', '\b', '\x2', '\x2', '\xE4', 
		'\xE6', '\x5', ' ', '\x11', '\x2', '\xE5', '\xE3', '\x3', '\x2', '\x2', 
		'\x2', '\xE6', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE5', '\x3', 
		'\x2', '\x2', '\x2', '\xE7', '\xE8', '\x3', '\x2', '\x2', '\x2', '\xE8', 
		'\xEA', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xE7', '\x3', '\x2', '\x2', 
		'\x2', '\xEA', '\xEB', '\a', '\a', '\x2', '\x2', '\xEB', '\xED', '\x3', 
		'\x2', '\x2', '\x2', '\xEC', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xEC', 
		'\xE1', '\x3', '\x2', '\x2', '\x2', '\xED', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\xEE', '\xEF', '\x5', '\x34', '\x1B', '\x2', '\xEF', '\xF0', '\x5', 
		'\x32', '\x1A', '\x2', '\xF0', '\xFA', '\x3', '\x2', '\x2', '\x2', '\xF1', 
		'\xF2', '\x5', '\x34', '\x1B', '\x2', '\xF2', '\xF3', '\x5', '\x32', '\x1A', 
		'\x2', '\xF3', '\xF5', '\a', '\x4', '\x2', '\x2', '\xF4', '\xF6', '\x5', 
		'\x30', '\x19', '\x2', '\xF5', '\xF4', '\x3', '\x2', '\x2', '\x2', '\xF5', 
		'\xF6', '\x3', '\x2', '\x2', '\x2', '\xF6', '\xF7', '\x3', '\x2', '\x2', 
		'\x2', '\xF7', '\xF8', '\a', '\x5', '\x2', '\x2', '\xF8', '\xFA', '\x3', 
		'\x2', '\x2', '\x2', '\xF9', '\xEE', '\x3', '\x2', '\x2', '\x2', '\xF9', 
		'\xF1', '\x3', '\x2', '\x2', '\x2', '\xFA', '!', '\x3', '\x2', '\x2', 
		'\x2', '\xFB', '\x103', '\x5', ',', '\x17', '\x2', '\xFC', '\x103', '\x5', 
		'.', '\x18', '\x2', '\xFD', '\x103', '\x5', '(', '\x15', '\x2', '\xFE', 
		'\x103', '\x5', '$', '\x13', '\x2', '\xFF', '\x103', '\x5', '&', '\x14', 
		'\x2', '\x100', '\x103', '\x5', '\x18', '\r', '\x2', '\x101', '\x103', 
		'\x5', '*', '\x16', '\x2', '\x102', '\xFB', '\x3', '\x2', '\x2', '\x2', 
		'\x102', '\xFC', '\x3', '\x2', '\x2', '\x2', '\x102', '\xFD', '\x3', '\x2', 
		'\x2', '\x2', '\x102', '\xFE', '\x3', '\x2', '\x2', '\x2', '\x102', '\xFF', 
		'\x3', '\x2', '\x2', '\x2', '\x102', '\x100', '\x3', '\x2', '\x2', '\x2', 
		'\x102', '\x101', '\x3', '\x2', '\x2', '\x2', '\x103', '#', '\x3', '\x2', 
		'\x2', '\x2', '\x104', '\x105', '\a', '/', '\x2', '\x2', '\x105', '\x106', 
		'\a', '\x3', '\x2', '\x2', '\x106', '%', '\x3', '\x2', '\x2', '\x2', '\x107', 
		'\x108', '\a', '.', '\x2', '\x2', '\x108', '\x109', '\a', '\x3', '\x2', 
		'\x2', '\x109', '\'', '\x3', '\x2', '\x2', '\x2', '\x10A', '\x10B', '\a', 
		'\x30', '\x2', '\x2', '\x10B', '\x10C', '\x5', '\x14', '\v', '\x2', '\x10C', 
		'\x10D', '\a', '\x3', '\x2', '\x2', '\x10D', ')', '\x3', '\x2', '\x2', 
		'\x2', '\x10E', '\x10F', '\x5', '\x14', '\v', '\x2', '\x10F', '\x110', 
		'\a', '\x3', '\x2', '\x2', '\x110', '+', '\x3', '\x2', '\x2', '\x2', '\x111', 
		'\x112', '\a', '+', '\x2', '\x2', '\x112', '\x113', '\a', '\x6', '\x2', 
		'\x2', '\x113', '\x114', '\x5', '\x14', '\v', '\x2', '\x114', '\x115', 
		'\a', '\a', '\x2', '\x2', '\x115', '\x116', '\x5', '\"', '\x12', '\x2', 
		'\x116', '\x117', '\a', ',', '\x2', '\x2', '\x117', '\x118', '\x5', '\"', 
		'\x12', '\x2', '\x118', '\x120', '\x3', '\x2', '\x2', '\x2', '\x119', 
		'\x11A', '\a', '+', '\x2', '\x2', '\x11A', '\x11B', '\a', '\x6', '\x2', 
		'\x2', '\x11B', '\x11C', '\x5', '\x14', '\v', '\x2', '\x11C', '\x11D', 
		'\a', '\a', '\x2', '\x2', '\x11D', '\x11E', '\x5', '\"', '\x12', '\x2', 
		'\x11E', '\x120', '\x3', '\x2', '\x2', '\x2', '\x11F', '\x111', '\x3', 
		'\x2', '\x2', '\x2', '\x11F', '\x119', '\x3', '\x2', '\x2', '\x2', '\x120', 
		'-', '\x3', '\x2', '\x2', '\x2', '\x121', '\x122', '\a', '-', '\x2', '\x2', 
		'\x122', '\x123', '\a', '\x6', '\x2', '\x2', '\x123', '\x124', '\x5', 
		'\x14', '\v', '\x2', '\x124', '\x125', '\a', '\a', '\x2', '\x2', '\x125', 
		'\x126', '\x5', '\"', '\x12', '\x2', '\x126', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x127', '\x128', '\a', '\x32', '\x2', '\x2', '\x128', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\x129', '\x12A', '\a', '\x31', '\x2', '\x2', 
		'\x12A', '\x33', '\x3', '\x2', '\x2', '\x2', '\x12B', '\x12C', '\t', '\x2', 
		'\x2', '\x2', '\x12C', '\x35', '\x3', '\x2', '\x2', '\x2', '\x18', '\x39', 
		'=', 'J', 'R', '\x63', 'j', 'x', '\x7F', '\x84', '\xBC', '\xBE', '\xC5', 
		'\xD1', '\xD6', '\xDA', '\xDE', '\xE7', '\xEC', '\xF5', '\xF9', '\x102', 
		'\x11F',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Frontend
