//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Program.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ProgramParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface IProgramVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ProgramParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecl([NotNull] ProgramParser.DeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_decl([NotNull] ProgramParser.Var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_expr([NotNull] ProgramParser.Primary_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.postfix_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfix_expr([NotNull] ProgramParser.Postfix_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.argument_expr_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument_expr_list([NotNull] ProgramParser.Argument_expr_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.unary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_expr([NotNull] ProgramParser.Unary_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.multiplicative_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicative_expr([NotNull] ProgramParser.Multiplicative_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.additive_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditive_expr([NotNull] ProgramParser.Additive_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.sft_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSft_expr([NotNull] ProgramParser.Sft_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.relational_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelational_expr([NotNull] ProgramParser.Relational_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpression([NotNull] ProgramParser.EqualityExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] ProgramParser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusiveOrExpression([NotNull] ProgramParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusiveOrExpression([NotNull] ProgramParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndExpression([NotNull] ProgramParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOrExpression([NotNull] ProgramParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalExpression([NotNull] ProgramParser.ConditionalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentExpression([NotNull] ProgramParser.AssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentOperator([NotNull] ProgramParser.AssignmentOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] ProgramParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.func_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_def([NotNull] ProgramParser.Func_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.compound_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound_stmt([NotNull] ProgramParser.Compound_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.block_item_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_item_list([NotNull] ProgramParser.Block_item_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.block_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_item([NotNull] ProgramParser.Block_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.param_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam_list([NotNull] ProgramParser.Param_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] ProgramParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] ProgramParser.StmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.continue_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinue_stmt([NotNull] ProgramParser.Continue_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.break_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreak_stmt([NotNull] ProgramParser.Break_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_stmt([NotNull] ProgramParser.Return_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.expr_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_stmt([NotNull] ProgramParser.Expr_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.selection_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection_stmt([NotNull] ProgramParser.Selection_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.iteration_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIteration_stmt([NotNull] ProgramParser.Iteration_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum([NotNull] ProgramParser.NumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] ProgramParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProgramParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_spec([NotNull] ProgramParser.Type_specContext context);
}
