//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Program.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Backend {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IProgramListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ProgramBaseListener : IProgramListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] ProgramParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] ProgramParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.funcDefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDefs([NotNull] ProgramParser.FuncDefsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.funcDefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDefs([NotNull] ProgramParser.FuncDefsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.decls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecls([NotNull] ProgramParser.DeclsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.decls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecls([NotNull] ProgramParser.DeclsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] ProgramParser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] ProgramParser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] ProgramParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] ProgramParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecl([NotNull] ProgramParser.DeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecl([NotNull] ProgramParser.DeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.funcDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDecl([NotNull] ProgramParser.FuncDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.funcDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDecl([NotNull] ProgramParser.FuncDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.globalVariableDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalVariableDecl([NotNull] ProgramParser.GlobalVariableDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.globalVariableDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalVariableDecl([NotNull] ProgramParser.GlobalVariableDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.variableDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDecl([NotNull] ProgramParser.VariableDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.variableDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDecl([NotNull] ProgramParser.VariableDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.paramDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamDecl([NotNull] ProgramParser.ParamDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.paramDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamDecl([NotNull] ProgramParser.ParamDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.funcTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncTail([NotNull] ProgramParser.FuncTailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.funcTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncTail([NotNull] ProgramParser.FuncTailContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.funcHead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncHead([NotNull] ProgramParser.FuncHeadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.funcHead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncHead([NotNull] ProgramParser.FuncHeadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.funcDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDef([NotNull] ProgramParser.FuncDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.funcDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDef([NotNull] ProgramParser.FuncDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.quaternary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuaternary([NotNull] ProgramParser.QuaternaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.quaternary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuaternary([NotNull] ProgramParser.QuaternaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperand([NotNull] ProgramParser.OperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperand([NotNull] ProgramParser.OperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary([NotNull] ProgramParser.UnaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary([NotNull] ProgramParser.UnaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.literalAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralAssignment([NotNull] ProgramParser.LiteralAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.literalAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralAssignment([NotNull] ProgramParser.LiteralAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableAssignment([NotNull] ProgramParser.VariableAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableAssignment([NotNull] ProgramParser.VariableAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinary([NotNull] ProgramParser.BinaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinary([NotNull] ProgramParser.BinaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>variableReturn</c>
	/// labeled alternative in <see cref="ProgramParser.return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableReturn([NotNull] ProgramParser.VariableReturnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>variableReturn</c>
	/// labeled alternative in <see cref="ProgramParser.return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableReturn([NotNull] ProgramParser.VariableReturnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>literalReturn</c>
	/// labeled alternative in <see cref="ProgramParser.return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralReturn([NotNull] ProgramParser.LiteralReturnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>literalReturn</c>
	/// labeled alternative in <see cref="ProgramParser.return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralReturn([NotNull] ProgramParser.LiteralReturnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.jumpEqual"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpEqual([NotNull] ProgramParser.JumpEqualContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.jumpEqual"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpEqual([NotNull] ProgramParser.JumpEqualContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] ProgramParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] ProgramParser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] ProgramParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] ProgramParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.end"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnd([NotNull] ProgramParser.EndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.end"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnd([NotNull] ProgramParser.EndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] ProgramParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] ProgramParser.VariableContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Backend
